CREATE TABLE `T_PRH_DATA` (
  `USER_ID` int(20) unsigned NOT NULL COMMENT '用户ID',
  `SEQ_NO` int(20) NOT NULL COMMENT '轮候排位',
  `APPLY_NO` varchar(20) NOT NULL DEFAULT '' COMMENT '备案号',
  `NUM` tinyint(4) NOT NULL DEFAULT 0 COMMENT '申请人数',
  `PLACE` varchar(20) NOT NULL DEFAULT '' COMMENT '户籍所在区',
  PRIMARY KEY (`USER_ID`),
  KEY `INDEX_APPLY_NO` (`APPLY_NO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='轮候信息'